import React from 'react'
import { PolicyLayout } from '@/components/layout/PolicyLayout'

export const metadata = {
  title: 'Terms of Service | AyurGlow',
  description: 'Terms and Conditions for using AyurGlow website and services.',
}

export default function TermsOfServicePage() {
  return (
    <PolicyLayout title="Terms and Conditions" lastUpdated="April 17, 2024">
      <p className="italic">
        THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF INFORMATION TECHNOLOGY ACT, 2000 AND IS PUBLISHED IN ACCORDANCE WITH THE PROVISIONS OF APPLICABLE LAWS. THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURES.
      </p>

      <section>
        <h2 className="text-xl font-bold text-[#022C22] mt-8 mb-4 uppercase tracking-wide border-l-4 border-primary pl-4">1. INTRODUCTION</h2>
        <p>
          PLEASE READ THESE TERMS AND CONDITIONS (“T&C”) CAREFULLY. BY ACCESSING, BROWSING, OR USING AYURGLOW.IN OR ANY OTHER PLATFORM OF AYURGLOW (“COMPANY”), YOU AGREE TO BE BOUND BY ALL THE TERMS MENTIONED HEREUNDER.
        </p>
        <p>
          Only persons who can enter into legally binding contract under the Indian Contract Act, 1872 can use the Website. Minors must use the platform under the supervision of a legal guardian.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-bold text-[#022C22] mt-8 mb-4 uppercase tracking-wide border-l-4 border-primary pl-4">2. PRODUCTS & SERVICES</h2>
        <p>
          The Website offers various Ayurvedic skincare products (“Products”). We endeavor to be as accurate as possible in our Product descriptions. However, colors, information, or other content may occasionally contain typographical errors or inaccuracies.
        </p>
        <p>
          We reserve the right to change, suspend, or discontinue any Product at any time without notice. Product prices are also subject to change without liability.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-bold text-[#022C22] mt-8 mb-4 uppercase tracking-wide border-l-4 border-primary pl-4">3. ACCOUNT RESPONSIBILITY</h2>
        <p>
          If you create an account on our platform, you are responsible for maintaining its confidentiality and for all activities that occur under your account. We reserve the right to refuse service or terminate accounts if terms are violated.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-bold text-[#022C22] mt-8 mb-4 uppercase tracking-wide border-l-4 border-primary pl-4">4. PROPRIETARY RIGHTS</h2>
        <p>
          All brand names, trademarks, and trade dress on this platform are the exclusive property of AyurGlow. You shall not copy, reproduce, or redistribute any Product or material found on this platform without express written authorization.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-bold text-[#022C22] mt-8 mb-4 uppercase tracking-wide border-l-4 border-primary pl-4">5. USER CONDUCT</h2>
        <p>
          You agree not to use the Website for any illegal purposes or to disrupt the enjoyment of the Website by other users. You are prohibited from violating the security of the Platform, including unauthorized access to data or systems.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-bold text-[#022C22] mt-8 mb-4 uppercase tracking-wide border-l-4 border-primary pl-4">6. LIMITATION OF LIABILITY</h2>
        <p>
          AyurGlow shall not be liable for any direct, indirect, or consequential damages resulting from the use or inability to use our products or services. Our total liability shall not exceed the amount paid by you for the specific product in question.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-bold text-[#022C22] mt-8 mb-4 uppercase tracking-wide border-l-4 border-primary pl-4">7. CONTACT INFORMATION</h2>
        <p>
          For any queries regarding these terms, please contact us at:
        </p>
        <div className="bg-[#F1F5F9] p-4 rounded-lg mt-4 text-sm">
          <p><strong>AyurGlow Aesthetics</strong></p>
          <p>Shop No 1,2 Ground Floor, Hotel Amreli Inn, Station Road, Amreli – 365601</p>
          <p><strong>Email:</strong> binaaesthetic05@gmail.com</p>
          <p><strong>Phone:</strong> +91 91060 20550</p>
        </div>
      </section>
    </PolicyLayout>
  )
}
